CREATE CLASS Station EXTENDS V;
CREATE PROPERTY Station.stationId INTEGER (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Station.stationName STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE INDEX Station.stationId UNIQUE;

CREATE CLASS LEDS_TO EXTENDS E;
CREATE PROPERTY LEADS_TO.length FLOAT;
