CREATE CLASS Station EXTENDS V;
CREATE PROPERTY Station.stationId INTEGER (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Station.stationName STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Station.latitude FLOAT;
CREATE PROPERTY Station.longtitude FLOAT;
CREATE INDEX Station.stationId UNIQUE;

CREATE CLASS LEADS_TO EXTENDS E;
CREATE PROPERTY LEADS_TO.length FLOAT;
