CREATE CLASS Product EXTENDS V;
CREATE PROPERTY Product.productId INTEGER (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Product.price INTEGER;
CREATE PROPERTY Product.productName STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE INDEX Product.productId UNIQUE;

CREATE CLASS Gender EXTENDS V;
CREATE PROPERTY Gender.genderName STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE INDEX Gender.genderName UNIQUE;

CREATE CLASS Brand EXTENDS V;
CREATE PROPERTY Brand.brandName STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE INDEX Brand.brandName UNIQUE;

CREATE CLASS BOUGHT_WITH EXTENDS E;
CREATE CLASS DEDICATED_TO EXTENDS E;
CREATE CLASS MANUFACTURED_BY EXTENDS E;