FROM arangodb:latest

ENV ARANGO_ROOT_PASSWORD=root

COPY csv /csv/
COPY import.sh /import.sh
COPY youtube-import-test.sh /youtube-import-test.sh
COPY youtube-properties-import.sh /youtube-properties-import.sh