CREATE CLASS User EXTENDS V;
CREATE PROPERTY User.userId INTEGER (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY User.firstName STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY User.lastName STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE INDEX User.userId UNIQUE;

CREATE CLASS Destination EXTENDS V;
CREATE PROPERTY Destination.destinationId INTEGER (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Destination.destinationName STRING (MANDATORY TRUE, NOTNULL TRUE);

CREATE CLASS Country EXTENDS V;
CREATE PROPERTY Country.countryCode STRING (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Country.countryName STRING (MANDATORY TRUE, NOTNULL TRUE);

CREATE CLASS Journey EXTENDS V;
CREATE PROPERTY Journey.journeyId INTEGER (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Journey.journeyName STRING;
CREATE PROPERTY Journey.journeyStart DATE;
CREATE PROPERTY Journey.journeyEnd DATE;

CREATE CLASS TravelActivity EXTENDS V;
CREATE PROPERTY TravelActivity.activityName STRING (MANDATORY TRUE, NOTNULL TRUE);

CREATE CLASS Rating EXTENDS V;
CREATE PROPERTY Rating.ratingId INTEGER (MANDATORY TRUE, NOTNULL TRUE);
CREATE PROPERTY Rating.body STRING;
CREATE PROPERTY Rating.rating INTEGER;

CREATE CLASS FOLLOWS EXTENDS E;
CREATE CLASS IS_WITHIN EXTENDS E;
CREATE CLASS LED_TO EXTENDS E;
CREATE PROPERTY LED_TO.startDate DATE;
CREATE PROPERTY LED_TO.endDate DATE;
CREATE CLASS LIKES EXTENDS E;
CREATE CLASS LIVES_IN EXTENDS E;
CREATE CLASS OFFERS EXTENDS E;
CREATE CLASS PARTICIPATED EXTENDS E;
CREATE CLASS WROTE EXTENDS E;
CREATE CLASS ABOUT EXTENDS E;