// CREATE NODES REPRESENTING CITIES
CREATE (a:City {name: 'A'}),
       (b:City {name: 'B'}),
       (c:City {name: 'C'}),
       (d:City {name: 'D'}),
       (e:City {name: 'E'}),
       (f:City {name: 'F'}),
       (g:City {name: 'G'}),
       (a)-[:CONNECTED {distance: 50}]->(b),
       (c)-[:CONNECTED {distance: 75}]->(b),
       (a)-[:CONNECTED {distance: 82}]->(c),
       (d)-[:CONNECTED {distance: 95}]->(c),
       (e)-[:CONNECTED {distance: 36}]->(c),
       (a)-[:CONNECTED {distance: 120}]->(d),
       (b)-[:CONNECTED {distance: 90}]->(d),
       (e)-[:CONNECTED {distance: 85}]->(d),
       (e)-[:CONNECTED {distance: 45}]->(f),
       (f)-[:CONNECTED {distance: 63}]->(g),
       (g)-[:CONNECTED {distance: 12}]->(a);